pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS_ID = 'DOCKERHUB_CREDENTIALS_ID' // Make sure to replace with your actual DockerHub credentials ID
        IMAGE_NAME = 'qiushiwang0702/jenkins_test' // Replace with your actual Docker image name
        // Define the base major and minor version
        MAJOR_VERSION = '7'
        MINOR_VERSION = '30'
    }
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    // Construct the full version string by appending the Jenkins build number as the patch version
                    def fullVersion = "${env.MAJOR_VERSION}.${env.MINOR_VERSION}.${env.BUILD_NUMBER}"
                    // Build the Docker image with the constructed version tag
                    docker.build("${env.IMAGE_NAME}:${fullVersion}")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', env.DOCKERHUB_CREDENTIALS_ID) {
                        // Push the Docker image with the same version tag used in the build stage
                        def fullVersion = "${env.MAJOR_VERSION}.${env.MINOR_VERSION}.${env.BUILD_NUMBER}"
                        docker.image("${env.IMAGE_NAME}:${fullVersion}").push()
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'Build and push completed.'
        }
    }
}
